### ISSUE TITLE
`solve_l_triangular` too harsh?

### ISSUE THREAD

**Issue by tokahuke** [AtheMathmo/rulinalg#41] opened 2016-09-16 23:09 UTC
My program has been panicking when I invoke `solve_l_triangular` on this:

```
⎡                    1.68933665291405 0.0000000000000000027626478732696488⎤
⎣                  0.0210783862932372                   1.7853800754297995⎦

```
Ok, I know! This is technically not lower triangular. But could not `rulinalg` be a bit more forgiving? Besides, there is no way to tell the code "I know what I am doing. Carry on!". 

Alternatively, there is no easy way to force a matrix to be lower triangular, is there?

**Comment by AtheMathmo** [comment] 2016-09-16 23:34
Yes you are probably right on this one - though I'm not too sure what the tactic here is for other libraries.

I think at the very least we should make this a failure rather than a panic - so this would be captured by the `Result` instead of terminating the program. It also seems sensible to me to use some tolerance and check that `x < eps` rather than `x == T::zero()`. Picking that `eps` value could be a little tricky though.

There is no trivial way to force a matrix to be lower triangular, but you could do something like the following:

```
for (idx, row) in a.iter_rows_mut().enumerate() {
    for x in row[idx+1..].iter_mut() {
        *x = 0.0;
    }
}
```

I haven't tested this for oversights but hopefully the intent is clear :)

**Comment by Andlon** [comment] 2016-09-17 15:16
A bit tangential, but highly related. I don't know if it has been discussed before, but would it make any sense at all to solve these constraints on the type level? I.e., you'd have types `LowerTriangularSlice`, `UpperTriangularSlice`, `DiagonalSlice` etc, and you can extract them from a general matrix using appropriate methods (i.e. `my_matrix.lower_triangular_slice()` or similar). It opens up for extra optimizations, higher degree of compile-time verification and potentially less error handling on the part of the user. That said, it might be a can of worms as the number of different types required may explode, and it may certainly complicate implementation.

With regards to this particular issue, it would avoid the problem altogether. I.e:
```
// The user explicitly tells us to ignore any elements that do not 
// belong to the lower triangular part of the matrix, 
// whether they are zero or not
let A: Matrix<T> = general_matrix_that_is_actually_lower_triangular();
let x = A.lower_triangular_slice().solve(b); 

```
Note that what I'm proposing is not to abstract away the storage of this matrix. The `.solve()` function would internally just work with `Matrix<T>` types as it currently does. This would presumably purely be a change in the API, although it can be used to provide more optimal implementations in certain cases.

Haven't thought this fully through, just putting it out there for discussion.

**Comment by Andlon** [comment] 2016-09-17 15:31
There's (at least) one potential pitfall in my previous example. What if the user expects that his matrix is lower triangular, but actually isn't? Now, I'd argue that this is a bug in the code _preceding_ the call to `solve_l_triangular`, but it might make it harder for the user to detect the error, as we'll merrily go on our way and solve it anyway.

**Comment by AtheMathmo** [comment] 2016-09-17 16:31
I had planned to capture things like you describe using sparse representations - though really as a non-expert this may not be the best approach. I'm a little too concerned about API bloat to want to make your suggested change - although perhaps once more of the pieces fall in place this could be a worthwhile addition. For now I'd rather have users ensure their matrix fits the required conditions.

> Now, I'd argue that this is a bug in the code preceding the call to `solve_l_triangular`

This was my logic with the current panic case - but I think that as @tokahuke says it is too harsh right now and forces his program to panic despite having a numerically lower triangular matrix. Perhaps raising the tolerance and absorbing this case as a failure instead is the right move?

**Comment by Andlon** [comment] 2016-09-17 16:47
By sparse representations, do you mean specialized storage for each type of matrix, or a general sparse matrix (as in _sparse linear algebra_)? If the latter case, in my experience, you wouldn't consider a triangular matrix "sparse", as it'll still have roughly `(n^2)/2` number of non-zeros in the worst case. Sparse storage is only truly worth it once you have _significantly_ lower number of non-zeros compared to the number of elements in the matrix. A rule of thumb could perhaps be `O(n)` number of non-zeros. If you mean a specialized storage specifically for each type (i.e. some kind of TriangularMatrix type), I fear this may be detrimental to performance, since the memory access patterns are "less linear", in some sense. At least I've observed that most existing libraries do not make special data structures for triangular matrices.

> This was my logic with the current panic case - but I think that as @tokahuke says it is too harsh right now and forces his program to panic despite having a numerically lower triangular matrix. Perhaps raising the tolerance and absorbing this case as a failure instead is the right move?

Personally, I prefer simply to change the semantics: Instead of letting `solve_l_triangular` take a lower triangular _matrix_, it solves the system using the lower triangular _part_ of a matrix. This is essentially equivalent to my `lower_triangular_slice()` suggestion, but without introducing additional types. In other words, whether or not the matrix truly is lower triangular is suddenly irrelevant. Then we don't have to deal with tolerances at all. I think this makes sense, because if the user truly expects the matrix to actually _be_ lower triangular, this is an invariant of the code that _precedes_ the call to `solve_[...]`.

Interested to hear your thoughts on this!

**Comment by AtheMathmo** [comment] 2016-09-17 16:51
Thanks for your input on the sparse representations. I did indeed mean specialized storage - so a triangular matrix would be a `Vec` of only the component above/below (and including) the diagonal. It's interesting that this would be detrimental to performance - I assumed that if anything this would help as we need to load less into cache to read the `Matrix` and we can vectorize operations like addition more easily. However - if anything it is a relief that we don't need to do this!

I also agree with your suggestion. We should clearly document what this function does and simply remove the check (I'm pretty sure this wont invalidate the algorithm at all). I can probably make use of this change in other places where I am enforcing zeros to please this function.

**Comment by Andlon** [comment] 2016-09-17 16:57
The note about performance was a very strong assumption on my part. In fact, when I think about it, I think it may also be wrong.  I think you're in a much better position than I am to make statements about this, since you have more experience than I do with the implementation of dense linear algebra!

**Comment by AtheMathmo** [comment] 2016-09-17 17:02
Well either way we won't be implementing anything like that for a while! I much prefer your suggestion for now.

@tokahuke what do you think? We would modify the function to remove the check entirely and just assume the user wants us to solve for the lower half of the matrix - regardless of what is on top.

**Comment by tokahuke** [comment] 2016-09-17 21:37
Well, this really kept me thinking... red wire or green wire?

I will share my recent experience developing software with linalg... The first time I attempted it with "home-made" code, I did make the mistake of switching a `solve_l_triangular` for a `solve_u_triangular` and it was a quite painful bug to correct. So, yes... I would love that that compiler would have caught that for me.

Therefore, it seems to me that the main confusion a programmer would make is to cal solve lower to an upper, or vice-versa. This is a bug, not an exceptional situation, therefore `panic!` seems to be the model suitable to the case, instead of using results, for example. However, most real situations will feed "dirty" matrices to the code, just mine did. This happens a lot, for example if you are propagating Cholesky decompositions, as I am doing. At the same time, it is a horrible idea to fit any kind of arbitrary criterion there. The code would work *most* of the time and then, eventually it would panic because a matrix, for some reason got too dirty. This is very bad for testing.  

Besides, forcing the matrix to **always** be lower triangular is both a usability nuisance *and* a performance hindrance, since we just writing code to please the code.

So, yeah... despite my woes, I would remove it, or, maybe add a `solve_l_triangular_unchecked` (if the API is not too bloated). This seems to be the solution most in line with the Zen of Python "errors should not pass silently, unless explicitly silenced". Interestingly, the tradeoff we are facing here is very similar to that of `unsafe` code. Normally, the user "knows what he is doing". At the same time, I do not think it should be idiomatic to mark this new function as `unsafe` just because.

**Comment by AtheMathmo** [comment] 2016-09-17 21:51
I think you make a lot of good points - and I am somewhat convinced that the current PR (#42) is in fact a step in the wrong direction. Rust helps us guide users away from bugs and this feels like the opposite.

Unless I am misunderstanding - you are suggesting that we should keep this to a hard zeroed check? I am not sure that this is the best (or most idiomatic) approach but it is certainly easier!

We could handle this slightly differently by modifying the API a little. Right now the solvers use a private function `forward_substitution`/`back_substitution` to compute the actual solution (and check for lack of solutions). We could expose this function and use this as our `solve_l_triangular_unchecked` while ensuring that `solve_l_triangular` does the hard/soft tolerance checking. I'm not too sure how I feel about changing the API like this but it is certainly an option.

Finally we could enforce this in the type system by adding the `TriangularMatrix` types (with an enum to determine upper/lower) and returning these from LUP/Cholesky whilst providing functions to pull these from a `Matrix`. This is a lot more work but perhaps better if the performance isn't effected. The main down side is code bloat for the operator overloading - which is already a [pain-point](https://github.com/AtheMathmo/rulinalg/blob/ea77454d37c9a4e81f1cb22b753b5a132b9f8f1f/src/matrix/impl_ops.rs) in Rust for these sort of things.

**Comment by tokahuke** [comment] 2016-09-17 23:19
> Unless I am misunderstanding - you are suggesting that we should keep this to a hard zeroed check? I am not sure that this is the best (or most idiomatic) approach but it is certainly easier!

I am actually suggesting that we either cut it sharp or do no complain about it at all. The problem I see here is writing code that works 99,99% of the time and then crashes on a veeery special case. This is just hell. In other words, we need to be reaaly careful about where we draw the line.

Another thing that stroke me: the triangularity check is `O(n**2)`, the same order of the algorithm itself. How much faster can we get with unchecked?

>  The main down side is code bloat for the operator overloading - which is already a pain-point in Rust for these sort of things.

Should this not be an issue in its own right? This overloading grows quadratically for every new type that is put in. A quick idea that I have just come up with was to do something like this:

```rust
impl<T: 2dIndexable, U: 2dIndexable> Add<U> for T {
    type Output = Matrix<T>;

    ...
}
```
And then make all `Matrix`, `Diagonal`, etc.... `2dIndexable` or something. Would this help?

**Comment by AtheMathmo** [comment] 2016-09-18 00:11
Thanks for clarifying - have you had a chance to check PR #42 which adopts the no complaints route?

The triangularity check is certainly a big hit to performance - if we do want a check I am not sure how to avoid this.

> And then make all Matrix, Diagonal, etc.... 2dIndexable or something. Would this help?

The issue is that we have optimal overloads for all of these types and would like to take advantage of them. Doing this while utilizing vectorizing and cache usage can prove tricky. I mean for example that the `Triangular` overload would only want to modify the triangular portion of the `Matrix` and so `Add` requires half as many read and writes.

**Comment by Andlon** [comment] 2016-09-18 11:25
I think @tokahuke brings up some interesting real-world issues. I'll try to break down what I see as the different issues here.

#### Accidentally exchanging `solve_l_triangular` and `solve_u_triangular`
I think this brings up an issue with the naming of these functions. Their behavior is almost exactly "opposite", yet their names differ only by a single character. Perhaps this particular problem would be easier to spot if the full names `solve_lower_triangular` and `solve_upper_triangular` were used? This brings up the wider topic of abbreviations. Imagine you're a user that has never used `rulinalg`, and you want to solve a lower triangular system. Assuming abbreviation, would you expect the name of this method to be `solve_l_tri`, `solve_lower_tri`, `solve_l_triangular`, or something else entirely? I think this is not clear at all. My personal stance on abbreviations is the following: _abbreviate only when the abbreviation is a well-known convention_, otherwise use the full name.

#### "Very nearly" triangular matrices
@tokahuke brings up an example where his matrix is supposed to be triangular, but in reality some elements that should be identically zero, are only "very nearly" zero. I'm curious as to when such a situation would occur in the first place. Could someone bring up some examples on when this happens? I ask, because, assuming you start with two upper triangular matrices `U` and `V` that are exactly `0.0` on their zeroed parts, I believe the following operations will maintain this property (please correct me if I'm wrong):
- `U * V`
- `U + V`
- `U - V`
- `U.transpose()` yields a perfect (exactly 0.0) lower triangular matrix

What other operations would you normally do that would break the invariant? I just want to understand the problem better!

#### Performance overhead of checking the triangularity invariant
I'd like to add that this is particularly important if you are solving the system multiple times. Assuming that the matrix is unchanged, you're redundantly performing the check over and over and over again.

#### Enforcing the constraint in the type system
As @AtheMathmo points out, we cannot easily abstract over memory access operations, and so with fully specialized matrix storage types, we'll in practice have a combinatorial explosion of the number of operator overloads we'd need to implement.

I'd like to consider another way of modelling the problem. We have the following goals:
- Enforcing matrix properties such as lower triangular etc. in the type system
- Making sure we can only perform `.back_substitution()` for upper triangular matrices, and `.forward_substitution()` for lower triangular matrices.
- Avoiding checks when we can guarantee triangularity (for example, Cholesky returns triangular matrices, and as such, further checks on these should be unnecessary).
- ~~Optimized storage/performance~~. I think the only way to achieve this is by operator overload for all combinations, so let's not make this a goal for now.

The following is inspired by how `nalgebra` (Rust low-dimensional linear algebra library) models unit vectors and unit quaternions. See the [Unit](http://nalgebra.org/doc/nalgebra/struct.Unit.html) type.

Say we have something like
```
struct LowerTriangular<T> {
    inner: T
}

impl LowerTriangular<T> {
    pub fn unwrap(self) -> T;
}

impl<T> LowerTriangular<Matrix<T>> {
   // Panics if matrix is not perfectly lower triangular.
   pub fn from_matrix(mat: Matrix<T>) -> Self;
   // Panics if matrix is not lower triangular within given tolerance
   pub fn from_matrix_with_tolerance(mat: Matrix<T>, tolerance: T) -> Self;
   // Not sure if this should actually be unsafe or not
   unsafe pub fn from_matrix_unchecked(mat: Matrix<T>) -> Self;

   pub fn forward_substitution(&self, b: Vector<T>) -> Result<Vector<T>, Error>;
}

// Also for &Matrix<T> somehow, so it does not need to own the matrix...

// I'm not sure if this is a good idea, but if it works the way I've intended, 
// it'd let us use the overloads from Matrix<T> directly...
impl Deref for LowerTriangular<T> {
   type Target = T;
   pub fn deref(&self) -> &T;
}
```
This is just a rough sketch, and is fraught with problems. However, I hope it conveys my idea sufficiently well. Essentially, the idea is to provide a wrapper type for matrices. The wrapper itself thus enforces the constraints on the matrix (by checking upon construction of the wrapper). After this point, it can safely be used without any further checking. For functions which return lower triangular matrices, you would return `LowerTriangular<Matrix<T>>` instead of just `Matrix<T>`. If you have constructed a matrix of your own, you would typically call the `from_matrix`, but if you _really_ need performance, you can call the `unchecked` version.

One (of potentially many) problem with this particular approach, is that if you want to obtain a general matrix directly from a function which returns `Result<LowerTriangular<Matrix<T>>, Error>`, you might have to call `.unwrap().unwrap()` or so. But there may be ways to avoid/mitigate this.

I just want to stress that I put this out here so we can discuss it, not that I necessarily consider this the best solution (particularly since I don't know if it would work out the way I had in mind).

**Comment by Andlon** [comment] 2016-09-18 11:57
Addendum: I played around in [playground](https://is.gd/5BQiEj), and I realized that Rust will _not_ dereference the receiver for binary operators, so all the overloads from `Matrix<T>` would not apply directly through Deref, only the ones where `LowerTriangular<T>` is on the right side.

**Comment by tokahuke** [comment] 2016-09-20 17:15
@AtheMathmo  Sorry, I have been meddling with other stuff these days, so, due to the complications of life, I will only be able to take a deep look in this later this week.

@Andlon Nice stuff there! About nearly triangular matrices, the application where things went wrong were the following: I have obtained dirty R from the `qr` function of `Matrix<T>` and have propagated them. This is not a problem and worked well under my home-made linalg library, which I am substituting by `rulinalg`.  I am working with a square-root UKF, where the state covariance is propagated as the Cholesky decomp of the covariance matrix. One of the steps is to make a QR decomposition of a matrix and then use the R matrix to compose the final value. Thus, I have propagated the dirty matrices. When I tried to invert them at one point, I have obtained a panic. The workaround I have found was simply to use `invert`, and indeed that is not a big problem with *my* code, as the dimensions are low. Please note that the dirty matrices do not seem to have degraded the output of my filter in any perceptible way.

So... open an issue on `qr`? For me, the implementation is fine.

**Comment by AtheMathmo** [comment] 2016-10-02 08:07
I think we still need to figure out the action points from this issue.

- It seems that we should close #42 ? (That or resolve the documentation and merge?)
- I think @Andlon made some great points that we should perhaps carry forwards to a new issue.
- Do we need to address the QR implementation to produce 'clean' matrices? We could even solve this within #40 ...

**Comment by Andlon** [comment] 2016-10-03 10:06
> It seems that we should close #42 ? (That or resolve the documentation and merge?)
> I think @Andlon made some great points that we should perhaps carry forwards to a new issue.

I'd definitely like to explore modelling constraints in the type system more, at least! It would be neat to leverage Rust's strong type system here.

> Do we need to address the QR implementation to produce 'clean' matrices? We could even solve this within #40 ...

Yes, I think this can be addressed by #40. See [my latest comment](https://github.com/AtheMathmo/rulinalg/issues/40#issuecomment-251069421).

**Comment by AtheMathmo** [comment] 2016-10-03 10:56
I agree that using the type system should definitely be our plan for the future. But for now do we want to make any modifications?

**Comment by Andlon** [comment] 2016-10-03 11:15
If you want an immediate solution, I suggest merging your PR, perhaps with my suggested changes to the documentation? I think in any case it is better than the currently implemented solution (which uses an arbitrary tolerance).

**Comment by AtheMathmo** [comment] 2016-10-03 11:27
That seems reasonable to me - we get a performance gain but the user has to pay a little more attention.

**Comment by Andlon** [comment] 2016-10-03 12:22
> That seems reasonable to me - we get a performance gain but the user has to pay a little more attention.

A performance gain, but hopefully also (with what I think is adequately clear documentation) also less surprises for the user, since the function currently uses an undocumented arbitrary tolerance which might come back to bite legitimate usecases, like that of @tokahuke in his original post here!

**Comment by AtheMathmo** [comment] 2016-10-03 13:07
I agree totally - I'll try to get this PR in before the end of the day.

**Comment by AtheMathmo** [comment] 2016-10-15 17:06
Closing for now - we will try to move towards a type enforced system later.

**Closed by AtheMathmo** 2016-10-15 17:06 UTC
